apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rmzy9rsrz-go 
  janus-idp.io/tekton: rmzy9rsrz-go
  backstage.io/kubernetes-id: rmzy9rsrz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rmzy9rsrz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml