apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rmzy9rsrz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rmzy9rsrz-go 
  name: rmzy9rsrz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rmzy9rsrz-go 
